#!/usr/bin/env ruby

require "pathname"
require "pp"
require "set"

data = []
input_path = Pathname("#{__dir__}/../data/input_03.txt")
input_path.readlines.map(&:chomp).each do |line|
  raise unless line =~ /\A#(\d+) @ (\d+),(\d+): (\d+)x(\d+)\z/
  data << [$1.to_i, $2.to_i, $3.to_i, $4.to_i, $5.to_i]
end

claims = {}
data.each do |elf, x0, y0, xsz, ysz|
  (x0...x0 + xsz).each do |x|
    (y0...y0 + ysz).each do |y|
      claims[[x, y]] ||= []
      claims[[x, y]] << elf
    end
  end
end

elves = data.map(&:first).to_set
bad_elves = claims.values.select { |v| v.size > 1 }.flatten.to_set

puts [*(elves - bad_elves)]
